---

- name: Adds Java via cask
  homebrew_cask:
    name: java
    state: "{{ desired_state }}"

- name: Adds homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: yes
  with_items:
    - mtr
    - tree
    - wget
    - git
    - dockutil
    - autoenv
    - graphviz
    - ant
