---

- name: Adds Java via cask
  homebrew_cask:
    name: java
    state: "{{ desired_state }}"

- name: Adds CheatSheet via cask
  homebrew_cask:
    name: cheatsheet
    state: "{{ desired_state }}"
  ignore_errors: yes

- name: Adds homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: latest
    update_homebrew: yes
