---

- name: Adds homebrew packages that do not require java
  homebrew:
    name: "{{ brew_packages }}"
    state: latest
    update_homebrew: yes

- name: Adds Java via cask
  homebrew_cask:
    name: java
    state: present

- name: Adds homebrew packages that require java
  homebrew:
    name: "{{ brew_packages_java }}"
    state: latest
    update_homebrew: yes
