---

- name: Customize iTerm2 PrefsCustomFolder
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "/Users/userlerueda/Documents/github/new_mac_setup/_data"

- name: Customize iTerm2 LoadPrefsFromCustomFolder
  osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true

- name: Customize iTerm2 NoSyncNeverRemindPrefsChangesLostForFile_selection
  osx_defaults:
    domain: com.googlecode.iterm2
    key: NoSyncNeverRemindPrefsChangesLostForFile_selection
    type: int
    value: 0
