dockitems_to_remove:
  - Launchpad
  - Safari
  - Contacts
  - Notes
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
